#!/bin/bash

export SCRIPT_DIR1=$(cd $(dirname $0); cd ../../../kails ;pwd)
export SCRIPT_DIR2=$(cd $(dirname $0); cd ../../../react-app ;pwd)

rm ./kails
cp ./base_script.txt ./kails
echo cd $SCRIPT_DIR1 >> ./kails
echo clear >> ./kails
chmod 755 ./kails

rm ./reactapp
cp ./base_script.txt ./reactapp
echo cd $SCRIPT_DIR2 >> ./reactapp
echo clear >> ./reactapp
chmod 755 ./reactapp

mkdir -p ~/bin
cp ./kails ~/bin
cp ./reactapp ~/bin